### ISSUE TITLE
App force closes after entering server URL and API key

### ISSUE THREAD

**Issue by freakshock88** [patzly/grocy-android#1]
Hi,

The app looks amazing, and works great in demo mode!

When I want to enter my own server details however, it force closes on me.
I tried local urls and my reverse proxy URL, with and without /api added to the URL.
The reverse proxy URL is the only one that seems to be accepted, but when loading the next screen the app force closes after 1 second. 

My url format is : https://grocy.mydomain.com

I'm using a OnePlus 5T with android version 9.

Any ideas? :)

**Comment by MrJohnZoidberg** [comment]
Hey, thanks for your compliments!
Do you have the latest grocy version 2.7 installed on your server?

The format of the url is fine, `/api` is appended internally.
Also disabling of feature flags is currently not supported, although in our test the app didn't crash with all flags disabled.

**Comment by MrJohnZoidberg** [comment]
If the app even crashes with the latest server version, it would help if you send the meaningful output of the `adb logcat` command after the crash / force close, because we couldn't reproduce it.
Ask if you need help with that :)

**Comment by freakshock88** [comment]
Thanks for your response. I do have the latest server version (running in docker).
I also tried using a default config, with no feature flags changed, but the app still crashes.
I sent you a logcat via email. Thanks!

**Comment by patzly** [comment]
I just released a new version with the possible fixes from @MrJohnZoidberg in the Play Store, let us know if it works :)

**Comment by freakshock88** [comment]
Unfortunately, it's not fixed after the update from the play store. I also tried another android device (a galaxy s4 tablet) and generating a new Grocy API key. Same issue. If you want another logcat let me know.

**Comment by patzly** [comment]
That's weird...
In version 0.9.3 I've enabled the debug logs for the first displayed fragment, in this case it's the stock overview where the crash apparently happens.
Can you send me a new logcat of the crash so I can take a look into that?

**Comment by freakshock88** [comment]
I see the new debug lines in the logcat indeed, I've sent them via email.

**Comment by patzly** [comment]
Another day, another version ;)
Please let us know if v1.0.0 works!

**Comment by freakshock88** [comment]
Well, the problem seems to have been on my side..
It did not work, even on version 1.0.

I then noticed I  suddenly could not open the products page of the webUI. 
I then deleted my DB and it worked again, so did you app.. Whoops! 
I think I might have corrupted the Grocy DB somehow. 

Thanks for all your effort though!

**Comment by patzly** [comment]
That's nice to hear! Enjoy :)
