### ISSUE TITLE
Bug: wrong conversation in barcode settings

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#611]
I have a product which is bought in crates and stored in bottles.
The conversation is 1 crate = 20 bottles.

When i set a barcode which coresponds to 1 bottle the app reports 

"this equals 500 crates"

I think this must a bug because on the grocy website it seem to be okay.

**Comment by dominiczedler** [comment]
<img src="https://user-images.githubusercontent.com/27244574/210177915-9f6230ed-94da-402c-bf36-dd4ef7318637.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210177932-a8c052c5-c477-4138-9b43-9ea7c2113db9.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210177856-1269231c-d3d7-4f3c-a1e4-52c847aab897.jpeg" width=300>

I tried to reproduce the issue but for me it works - Did you set your product properties differently?

**Comment by Saturo78** [comment]
Yes, i have checked everything twice.
The product settings are all okay and exactly the same as in your given example.

Additionally i had a coversation between Bottle and ml (1:500). When i delete this conversation it seem to be okay.

Could you please test again with this conversation?

**Comment by dominiczedler** [comment]
Thanks for your help! It should be fixed in the next nightly (I will build it manually in a few minutes).

**Comment by Saturo78** [comment]
I made a test with the nightly and i'm sorry but i have to report that the issue is still there. 
Can i provide any further informations?

**Comment by dominiczedler** [comment]
I've tried it again like above and with the additional conversion to Milliliters:

<img src="https://user-images.githubusercontent.com/27244574/210275265-099078ae-05f0-41c9-b549-d8fc3d3ab26e.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210177915-9f6230ed-94da-402c-bf36-dd4ef7318637.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210177932-a8c052c5-c477-4138-9b43-9ea7c2113db9.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210275397-73261801-e024-491d-b4aa-90a5dd7b1051.jpeg" width=300>

<img src="https://user-images.githubusercontent.com/27244574/210275562-e21edf01-4f9a-4ebb-ba57-fbeadab15dc2.jpeg" width=300>

Maybe you can uninstall the app first and reinstall the nightly? I heard from other users that the nightly changes are not applied if you "update" the app with the APK, I think because there is no internal version change.

**Comment by Saturo78** [comment]
I always have to uninstall the old version otherwise the installation of the new version fails.

I will uninstall and try again.

**Comment by Saturo78** [comment]
Still the same result. No change.

![Screenshot_20230102_215212_Grocy.jpg](https://user-images.githubusercontent.com/71584438/210277266-d18175f4-0703-4860-b0d2-85e2d169ce9d.jpg)

Don´t now if its important, the test product is a child product.

**Comment by dominiczedler** [comment]
I'm sorry, I forgot to upload the changes of one important file... I will build the nightly again, this time the other issue with the barcode info copy feature should be also on board (a new option in behaviour settings).
